---
dependency:
  name: galaxy
driver:
  name: docker
#lint: |
#  set -e
#  yamllint .
#  ansible-lint molecule/default/*.yml tasks/*.yml


platforms:
  - name: instance
   # image: docker.io/pycontribs/centos:7
    image: geerlingguy/docker-centos7-ansible:latest
    #command: bash -c "while true;do sleep 1000;done"
    command: "/usr/lib/systemd/systemd"
    #tmpfs:
    #  - /run
    #  - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
 # env:
  #  MOLECULE_INVENTORY_FILE: ../../tests/inventory
   
verifier:
  name: testinfra
  options:
    # show which tests where executed in test output
    v: 1
